import { type ChangeEvent, type FormEvent, type ReactNode, useState } from 'react';
import { FileImage, FileText, Sparkles } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { extractFromImage, extractFromText } from '../services/extraction-service';
import { createItem } from '../services/item-service';
import type { ExtractedItem, ItemDraft, ItemStatus, ItemType } from '../types/item';
import { useToast } from '../components/ToastProvider';
import { ConfidenceExplanation } from '../components/ConfidenceExplanation';
import { normalizeCurrency } from '../utils/currency';

const types: ItemType[] = ['SUBSCRIPTION', 'BILL', 'WARRANTY', 'APPOINTMENT', 'OTHER']; const statuses: ItemStatus[] = ['ACTIVE', 'NEEDS_REVIEW', 'CANCELLED', 'EXPIRED']; const maxBytes = 10 * 1024 * 1024;
const toDate = (value: string | null) => value?.slice(0, 10) ?? '';
const draftFrom = (item: ExtractedItem, sourceType: ItemDraft['sourceType'], sourceRawText: string | null): ItemDraft => ({ ...item, type: item.type ?? 'OTHER', merchant: item.merchant ?? item.vendorName ?? '', subscription: item.subscription ?? '', currency: normalizeCurrency(item.currency), notes: item.notes ?? '', sourceType, sourceRawText });
export function UploadPage() {
  const navigate = useNavigate(); const { success } = useToast(); const [mode, setMode] = useState<'image' | 'text'>('image'); const [file, setFile] = useState<File | null>(null); const [text, setText] = useState(''); const [draft, setDraft] = useState<ItemDraft | null>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const set = <K extends keyof ItemDraft>(key: K, value: ItemDraft[K]) => setDraft((current) => current ? { ...current, [key]: value } : current);
  function chooseFile(event: ChangeEvent<HTMLInputElement>) { const next = event.target.files?.[0] ?? null; if (!next) return setFile(null); if (!['image/png', 'image/jpeg'].includes(next.type)) return setError('Only PNG, JPG, and JPEG images are supported.'); if (next.size > maxBytes) return setError('The image must be 10 MB or smaller.'); setError(null); setFile(next); }
  async function extract(event: FormEvent) { event.preventDefault(); setError(null); setBusy(true); try { setDraft(mode === 'image' ? draftFrom(await extractFromImage(file ?? (() => { throw new Error('Choose an image first.'); })()), 'PHOTO', null) : draftFrom(await extractFromText(text), 'EMAIL', text)); success('Details extracted. Review them before saving.'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not extract information. Please enter manually.'); } finally { setBusy(false); } }
  async function save(event: FormEvent) { event.preventDefault(); if (!draft) return; setBusy(true); setError(null); try { await createItem({ ...draft, renewalDate: draft.renewalDate ? new Date(`${toDate(draft.renewalDate)}T00:00:00.000Z`).toISOString() : null, cancelByDate: draft.cancelByDate ? new Date(`${toDate(draft.cancelByDate)}T00:00:00.000Z`).toISOString() : null, currency: normalizeCurrency(draft.currency), notes: draft.notes?.trim() || null }); success('Record saved to Tendly.'); navigate('/'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to save the record.'); } finally { setBusy(false); } }
  if (draft) return <div className="review-page"><div className="detail-head"><div><span className="eyebrow">Review extraction</span><h1>Confirm the details</h1><p>Everything can be edited before it becomes a saved record.</p></div><ConfidenceExplanation item={draft} /></div><form className="form-card" onSubmit={save}><div className="form-grid"><Field label="Vendor"><input required value={draft.vendorName ?? ''} onChange={(event) => { set('vendorName', event.target.value); set('merchant', event.target.value); }} /></Field><Field label="Type"><select value={draft.type ?? 'OTHER'} onChange={(event) => set('type', event.target.value as ItemType)}>{types.map((value) => <option key={value}>{value}</option>)}</select></Field><Field label="Subscription / plan"><input value={draft.subscription ?? ''} onChange={(event) => set('subscription', event.target.value)} /></Field><Field label="Amount"><input type="number" min="0" step="0.01" value={draft.amount ?? ''} onChange={(event) => set('amount', event.target.value ? Number(event.target.value) : null)} /></Field><Field label="Currency"><input value={draft.currency ?? ''} onChange={(event) => set('currency', event.target.value.toUpperCase() || null)} /></Field><Field label="Status"><select value={draft.status} onChange={(event) => set('status', event.target.value as ItemStatus)}>{statuses.map((value) => <option key={value}>{value}</option>)}</select></Field><Field label="Renewal date"><input type="date" value={toDate(draft.renewalDate)} onChange={(event) => set('renewalDate', event.target.value || null)} /></Field><Field label="Cancel by"><input type="date" value={toDate(draft.cancelByDate)} onChange={(event) => set('cancelByDate', event.target.value || null)} /></Field></div><Field label="Notes"><textarea rows={5} value={draft.notes ?? ''} onChange={(event) => set('notes', event.target.value || null)} /></Field>{error && <div className="inline-error">{error}</div>}<div className="form-actions"><button type="button" className="button secondary" onClick={() => setDraft(null)}>Start over</button><button className="button primary" disabled={busy}>{busy ? 'Saving…' : 'Save record'}</button></div></form></div>;
  return <div className="upload-page"><section className="page-hero"><div><span className="eyebrow">New record</span><h1>Turn a document into a reminder.</h1><p>Upload a receipt, bill, or warranty card—or paste an email—to create a record in seconds.</p></div></section><form className="upload-card" onSubmit={extract}><div className="mode-tabs"><button type="button" className={mode === 'image' ? 'selected' : ''} onClick={() => setMode('image')}><FileImage size={18} />Upload image</button><button type="button" className={mode === 'text' ? 'selected' : ''} onClick={() => setMode('text')}><FileText size={18} />Paste email</button></div>{mode === 'image' ? <label className="drop-zone"><FileImage size={30} /><strong>{file ? file.name : 'Drop your document here'}</strong><span>{file ? 'Ready to extract. You can choose another image below.' : 'Choose a clear image of a receipt, bill, subscription, or warranty.'}</span><small>PNG, JPG, or JPEG · maximum 10 MB</small><input type="file" accept="image/png,image/jpeg" onChange={chooseFile} /></label> : <Field label="Email text"><textarea rows={12} value={text} onChange={(event) => setText(event.target.value)} placeholder="Paste the relevant email content here…" /></Field>}{error && <div className="inline-error">{error}</div>}<button className="button primary full" disabled={busy}><Sparkles size={17} />{busy ? 'Extracting…' : 'Extract details'}</button></form></div>;
}
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="field"><span>{label}</span>{children}</label>; }
